version: "3.8"

services:
  DailyhotApi:
    container_name: dailyhotapi
    build:
      context: .
      target: runner
    ports:
      - "6088:6088"
    volumes:
      - "./logs:/app/logs"
    environment:
      - PORT=6088
      - REQUEST_TIMEOUT=6000
      - CACHE_TTL=600
    user: "114514"
    restart: always
